[package]
name = "server_monitor"
version = "0.1.0"
authors = ["Hiroaki Goto <goto.inct@gmail.com>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
regex = "0.2"
procinfo = "0.4"
libc = "0.2"
itertools = "0.7"